version: "3.8"
services:
  python:
    container_name: python
    image: python-dev:ExoKneeSpringParam
    build: 
      context: .
      dockerfile: Dockerfile
      args:
        USER_ID: ${USER_ID}   # Pass current user at build to avoid file permissions issues
        GROUP_ID: ${GROUP_ID}  # Pass current group at build to avoid file permissions issues
    env_file: 
      - build.env
      - display.env
    volumes:
      - ../.:/home/user/ws
      - /tmp/.X11-unix:/tmp/.X11-unix               # For display
      - /tmp/.docker.xauth:/tmp/.docker.xauth:rw    # For display
      - /run/user/1000:/run/user/1000               # For display

    # For attaching shells
    stdin_open: true # docker run -i
    tty: true        # docker run -t

    # Environment Variables
    environment:
      - DISPLAY=${DISPLAY}  # Echoing DISPLAY variable in scripts returns 1, so you need to specify here (should work for most or all devices)
      - XAUTHORITY=${XAUTH}
      - QT_X11_NO_MITSHM=1

    # Startup Command
    network_mode: "host"
    privileged: true
    user: user
    # Required for ptrace-based debuggers like C++, Go, and Rust
    cap_add:
    - SYS_PTRACE
    security_opt:
    - seccomp:unconfined

    # Startup Command
    # command: bash -c 